apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: debug-app
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      enabled: true
  source:
    repoURL: https://github.com/ppapapetrou76/argocd-playground.git
    targetRevision: HEAD
    path: ./apps/issue-26330

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
