apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: all-apps
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
spec:
  project: default
  source:
    repoURL: https://github.com/ppapapetrou76/argocd-playground.git
    targetRevision: HEAD
    path: apps/issue-26954
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
