---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trivial-go-web-app
  template:
    metadata:
      labels:
        app: simple-deployment
    spec:
      containers:
        - name: busybox
          image: busybox
          command: ["sleep", "infinity"]
          env:
            - name: FOO
              value: "{{ .Values.run }}"
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - |
                  if [ ! -f /tmp/ready ]; then
                    sleep 20 && touch /tmp/ready &
                    exit 1
                  else
                    exit 0
                  fi
            initialDelaySeconds: 0
            periodSeconds: 5