apiVersion: batch/v1
kind: Job
metadata:
  name: simple-app-delete-cm
  annotations:
    argocd.argoproj.io/hook: PostDelete
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: simple-app-sa
      containers:
        - name: delete-configmap
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              kubectl delete configmap simple-app-cm --namespace postdelete -
      restartPolicy: OnFailure
