---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: simple-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: simple-app
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "update", "get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: simple-app
subjects:
  - kind: ServiceAccount
    name: simple-app
roleRef:
  kind: Role
  name: simple-app
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: simple-app
spec:
  template:
    spec:
      serviceAccountName: simple-app
      containers:
        - name: create-configmap
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              kubectl create configmap simple-app-cm --from-literal=foo=bar --dry-run=client -o yaml | kubectl apply -f -
      restartPolicy: OnFailure
