---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: simple-service-account-prune
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
