apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: sx-wkr--cl001-kyverno
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    helm:
      ignoreMissingValueFiles: true
      releaseName: sx-kyverno
    path: platform-apps/charts/kyverno
    repoURL: https://github.com/suxess-it/kubriX.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      annotations:
        argocd.argoproj.io/tracking-id: sx-wkr--cl001-kyverno:app/Namespace:kyverno/kyverno
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true