apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-application
  # You'll usually want to add your resources to the argocd namespace.
  namespace: codefresh
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The project the application belongs to.
  project: default

  # Source of the application manifests
  source:
    repoURL: https://github.com/ppapapetrou76/gitops-cert-level-2-examples.git
    targetRevision: HEAD
    path: ./simple-application
   
    # directory
    directory:
      recurse: false
  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: default

